### ISSUE TITLE
how do i compile?

### ISSUE THREAD

**Issue by ghost** [OgarProject/Ogar2-Server#10]
please tell me how to compile the code.

**Comment by SmallJoker** [comment]
```
Once you've obtained a JAR file, either by compiling the source yourself or from downloading one of our precompiled builds
```

![Source](https://github.com/OgarProject/Ogar2-Server/blob/master/README.md#obtaining-and-using)

:+1: Please upload a binary to the releases section. Players prefer to download & start quickly without downloading the complete SDK first.

**Comment by ghost** [comment]
That doesn't tell me where to get the jar file.

**Comment by z3ntu** [comment]
see #11

**Comment by ghost** [comment]
i still do not have linux. LOOK I AM NEW HERE OK???

**Comment by z3ntu** [comment]
Seriously, get yourself a live-cd of Ubuntu and do it there, it's much easier; or just install Ubuntu (or any other Linux) on your PC.

**Comment by elitajmx** [comment]
https://github.com/OgarProject/Ogar2-Server/blob/master/README.md#obtaining-and-using
it says i need to run it in a command line, what command line??

**Comment by likcoras** [comment]
On Windows, install [Git](https://git-scm.com/), the lastest [Java](http://www.oracle.com/technetwork/java/javase/downloads/index.html) (Make sure it's the JDK, not the JRE). and (Maven)[]

**Comment by nevivurn** [comment]
On Windows, install [Git](https://git-scm.com/), the lastest [Java](http://www.oracle.com/technetwork/java/javase/downloads/index.html) (Make sure it's the JDK, not the JRE), and [Maven](https://maven.apache.org/) Just follow the instructions on each website and make a few searches if anything is unclear.

Then follow the instructions under [Obtaining and Using](https://github.com/OgarProject/Ogar2-Server/blob/master/README.md#obtaining-and-using) to get a .jar file and run it.

Although, it would be nice if there was a place where people could download official jarfiles from, since most people just can't be bothered with this. Maybe it's because it's still in development? (although there haven't been any updates for a while now).

**Comment by elitajmx** [comment]
someone should really make a video of this

**Comment by elitajmx** [comment]
I DONT KNOW HOW TO DO THIS PLASEEE HELP

**Comment by rsajeey** [comment]
@elitajmx, Use Ogar instead of Ogar2.

**Comment by ghost** [comment]
i give up on this
